changed link colour var to use specific link var rather than primary
localgovdrupal/localgov_theme pull request #81
Opened 2020-09-21 13:37 UTC by cjstevens78

2020-10-01 18:08 UTC, andybroomfield requested changes
The first part is working as expected, however the hover / focus colour is not working becuase it is overidden by the following in _shame.scss.
````scss
.access-background { 
  background-color: $focus;
  color: $secondary;
  text-decoration: none;
  box-shadow: 0 0 0 0.125rem $focus;
}
````

2020-10-06 14:20 UTC, cjstevens78 commented on assets/scss/lib/partials/_shame.scss
> -// // remove left hand border on google search results causing content to indent on hover
removed - croydon specific sass

2020-10-06 14:21 UTC, cjstevens78 commented on assets/scss/lib/partials/_shame.scss
> -// .gsc-webResult.gsc-result {
removed - croydon specific sass

2020-10-06 14:21 UTC, cjstevens78 commented on assets/scss/lib/partials/_shame.scss
> -// important:: fix form.io overriding this specific pseudo in the footer
removed - croydon specific sass

2020-10-06 15:38 UTC, andybroomfield approved these changes
This works for me and happy to see this changed merged.

2020-10-06 16:01 UTC, merged